SELECT USER
FROM DUAL;
--==>>SCOTT

--○ 실습 테이블 생성
CREATE TABLE TBL_STUDENT
( SID   NUMBER
, NAME  VARCHAR2(30)
, TEL   VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);
--==>>Table TBL_STUDENT이(가) 생성되었습니다.

--○ 샘플 데이터 입력
INSERT INTO TBL_STUDENT(SID, NAME, TEL) VALUES(1, '김경환', '010-1111-1111');
INSERT INTO TBL_STUDENT(SID, NAME, TEL) VALUES(2, '김선아', '010-2222-2222');
INSERT INTO TBL_STUDENT(SID, NAME, TEL) VALUES(3, '김성희', '010-3333-3333');
INSERT INTO TBL_STUDENT(SID, NAME, TEL) VALUES(4, '김정규', '010-4444-4444');
--==>>1 행 이(가) 삽입되었습니다.

--○ 실습 테이블 생성
CREATE TABLE TBL_GRADE
( SID   NUMBER
, SUB1  NUMBER(3)
, SUB2  NUMBER(3)
, SUB3  NUMBER(3)
, CONSTRAINT GRADE_SID_PK   PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK   FOREIGN KEY(SID) REFERENCES TBL_STUDENT(SID)
);
--==>>Table TBL_GRADE이(가) 생성되었습니다.

--○ 샘플 데이터 입력
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3) VALUES(1, 90, 80, 70);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3) VALUES(2, 70, 60, 50);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3) VALUES(3, 50, 40, 30);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3) VALUES(4, 90, 90, 30);
--==>>1 행 이(가) 삽입되었습니다.

--○ 커밋
COMMIT;
--==>>커밋 완료.

--○ 제약조건 추가
ALTER TABLE TBL_GRADE ADD CONSTRAINT GRADE_SUB1_CK CHECK(SUB1 BETWEEN 0 AND 100);
ALTER TABLE TBL_GRADE ADD CONSTRAINT GRADE_SUB2_CK CHECK(SUB2 BETWEEN 0 AND 100);
ALTER TABLE TBL_GRADE ADD CONSTRAINT GRADE_SUB3_CK CHECK(SUB3 BETWEEN 0 AND 100);

--○ 뷰 생성(STUDENTVIEW)
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT S.SID, S.NAME, S.TEL , G.SUB1
FROM TBL_STUDENT S JOIN TBL_GRADE G
ON S.SID = G.SID;


--○ 뷰 생성(GRADEVIEW)
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID, S.NAME, G.SUB1, G.SUB2, G.SUB3, (G.SUB1+G.SUB2+G.SUB3) AS TOT, (G.SUB1+G.SUB2+G.SUB3)/3 AS AVG
,      CASE WHEN SUB1<40 OR SUB2<40 OR SUB3<40 THEN '과락'
            WHEN ((G.SUB1+G.SUB2+G.SUB3)/3)<60 THEN '불합격'
            ELSE '합격'
        END AS CH
FROM TBL_STUDENT S JOIN TBL_GRADE G
ON S.SID=G.SID;



SELECT CASE WHEN SUB1<40 OR SUB2<40 OR SUB3<40 THEN '과락'
            WHEN ((G.SUB1+G.SUB2+G.SUB3)/3)<60 THEN '불합격'
            ELSE '합격'
        END
FROM TBL_STUDENT S JOIN TBL_GRADE G
ON S.SID=G.SID;

SELECT *
FROM GRADEVIEW;

SELECT *
FROM STUDENTVIEW;

SELECT *
FROM TBL_GRADE;

SELECT *
FROM TBL_STUDENT;

SELECT SID, NAME, TEL
FROM TBL_STUDENT
ORDER BY SID;

SELECT SID, SUB1, SUB2, SUB3
FROM TBL_GRADE
ORDER BY SID;

SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW;

